export const IDL = {
  address: "2Htsz7Xf4YWZTc8tupBTgsFHwZNZDzi59FRr9AWmxdNq",
  metadata: { name: "contract", version: "0.1.0", spec: "0.1.0" },
  instructions: [
    // ── Admin / Config ────────────────────────────────────────────────────────
    {
      name: "initializeConfig",
      discriminator: [208, 127, 21, 1, 194, 190, 196, 70],
      accounts: [
        { name: "admin", writable: true, signer: true },
        { name: "config", writable: true },
        { name: "systemProgram", address: "11111111111111111111111111111111" },
      ],
      args: [{ name: "aiAgent", type: "pubkey" }],
    },
    {
      name: "createMockMint",
      discriminator: [186, 150, 36, 212, 159, 183, 46, 144],
      accounts: [
        { name: "admin", writable: true, signer: true },
        { name: "config", writable: true },
        { name: "mint", writable: true },
        { name: "tokenProgram" },
        { name: "systemProgram", address: "11111111111111111111111111111111" },
      ],
      args: [],
    },
    {
      name: "mintUsdc",
      discriminator: [18, 18, 44, 151, 229, 134, 223, 5],
      accounts: [
        { name: "user", writable: true, signer: true },
        { name: "config", writable: true },
        { name: "mint", writable: true },
        { name: "userTokenAccount", writable: true },
        { name: "mintRecord", writable: true },
        { name: "tokenProgram" },
        { name: "associatedTokenProgram", address: "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" },
        { name: "systemProgram", address: "11111111111111111111111111111111" },
      ],
      args: [],
    },
    // ── Contract lifecycle ────────────────────────────────────────────────────
    {
      name: "createContract",
      discriminator: [244, 48, 244, 178, 216, 88, 122, 52],
      accounts: [
        { name: "client", writable: true, signer: true },
        { name: "contractor" },
        { name: "contract", writable: true },
        { name: "mint" },
        { name: "escrowTokenAccount", writable: true },
        { name: "clientTokenAccount", writable: true },
        { name: "tokenProgram" },
        { name: "associatedTokenProgram", address: "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" },
        { name: "systemProgram", address: "11111111111111111111111111111111" },
      ],
      args: [
        { name: "createdAt", type: "i64" },
        { name: "contractHash", type: "string" },
        { name: "aiReviewHash", type: "string" },
        { name: "totalAmount", type: "u64" },
        { name: "latePenaltyPerDayBps", type: "u16" },
        { name: "maxPenaltyBps", type: "u16" },
        { name: "disputeWindowDays", type: "u8" },
        { name: "gracePeriodDays", type: "u8" },
        { name: "maxRevisionsPerCheckpoint", type: "u8" },
        { name: "checkpoints", type: { vec: { defined: { name: "CheckpointInput" } } } },
      ],
    },
    {
      name: "acceptContract",
      discriminator: [217, 254, 164, 16, 244, 59, 30, 81],
      accounts: [
        { name: "contractor", signer: true },
        { name: "contract", writable: true },
      ],
      args: [],
    },
    {
      name: "submitCheckpoint",
      discriminator: [47, 64, 6, 25, 169, 125, 69, 117],
      accounts: [
        { name: "contractor", signer: true },
        { name: "contract", writable: true },
      ],
      args: [
        { name: "checkpointIndex", type: "u8" },
        { name: "evidenceHash", type: "string" },
      ],
    },
    {
      name: "approveCheckpoint",
      discriminator: [250, 243, 123, 242, 101, 200, 73, 95],
      accounts: [
        { name: "client", writable: true, signer: true },
        { name: "contractor" },
        { name: "contract", writable: true },
        { name: "mint" },
        { name: "escrowTokenAccount", writable: true },
        { name: "contractorTokenAccount", writable: true },
        { name: "clientTokenAccount", writable: true },
        { name: "tokenProgram" },
      ],
      args: [
        { name: "checkpointIndex", type: "u8" },
        { name: "aiReportHash", type: "string" },
      ],
    },
    {
      name: "claimCheckpoint",
      discriminator: [22, 72, 57, 5, 103, 92, 116, 231],
      accounts: [
        { name: "contractor", writable: true, signer: true },
        { name: "client" },
        { name: "contract", writable: true },
        { name: "mint" },
        { name: "escrowTokenAccount", writable: true },
        { name: "contractorTokenAccount", writable: true },
        { name: "clientTokenAccount", writable: true },
        { name: "tokenProgram" },
      ],
      args: [{ name: "checkpointIndex", type: "u8" }],
    },
    {
      name: "requestRevision",
      discriminator: [205, 195, 75, 171, 242, 149, 90, 14],
      accounts: [
        { name: "client", signer: true },
        { name: "contractor" },
        { name: "contract", writable: true },
      ],
      args: [
        { name: "checkpointIndex", type: "u8" },
        { name: "aiReportHash", type: "string" },
      ],
    },
    {
      name: "requestExtension",
      discriminator: [231, 210, 223, 82, 160, 62, 136, 88],
      accounts: [
        { name: "contractor", signer: true },
        { name: "client" },
        { name: "contract", writable: true },
      ],
      args: [
        { name: "checkpointIndex", type: "u8" },
        { name: "newDeadline", type: "i64" },
      ],
    },
    {
      name: "approveExtension",
      discriminator: [202, 138, 100, 241, 89, 154, 3, 53],
      accounts: [
        { name: "client", signer: true },
        { name: "contractor" },
        { name: "contract", writable: true },
      ],
      args: [{ name: "checkpointIndex", type: "u8" }],
    },
    {
      name: "rejectExtension",
      discriminator: [103, 229, 117, 220, 156, 164, 244, 241],
      accounts: [
        { name: "client", signer: true },
        { name: "contractor" },
        { name: "contract", writable: true },
      ],
      args: [{ name: "checkpointIndex", type: "u8" }],
    },
    {
      name: "expireCheckpoint",
      discriminator: [107, 232, 48, 207, 145, 219, 235, 237],
      accounts: [
        { name: "client", writable: true, signer: true },
        { name: "contractor" },
        { name: "contract", writable: true },
        { name: "mint" },
        { name: "escrowTokenAccount", writable: true },
        { name: "clientTokenAccount", writable: true },
        { name: "tokenProgram" },
      ],
      args: [{ name: "checkpointIndex", type: "u8" }],
    },
    {
      name: "cancelContract",
      discriminator: [3, 168, 37, 73, 140, 194, 156, 165],
      accounts: [
        { name: "client", writable: true, signer: true },
        { name: "contractor" },
        { name: "contract", writable: true },
        { name: "mint" },
        { name: "escrowTokenAccount", writable: true },
        { name: "clientTokenAccount", writable: true },
        { name: "tokenProgram" },
      ],
      args: [],
    },
    {
      name: "requestAiReview",
      discriminator: [91, 246, 52, 188, 130, 19, 83, 250],
      accounts: [
        { name: "contractor", signer: true },
        { name: "contract", writable: true },
      ],
      args: [{ name: "checkpointIndex", type: "u8" }],
    },
    {
      name: "adminCancel",
      discriminator: [34, 225, 37, 131, 38, 121, 43, 237],
      accounts: [
        { name: "admin", writable: true, signer: true },
        { name: "client" },
        { name: "contractor" },
        { name: "contract", writable: true },
        { name: "config" },
        { name: "mint" },
        { name: "escrowTokenAccount", writable: true },
        { name: "clientTokenAccount", writable: true },
        { name: "tokenProgram" },
      ],
      args: [],
    },
    {
      name: "resolveDispute",
      discriminator: [231, 6, 202, 6, 96, 103, 12, 230],
      accounts: [
        { name: "resolver", writable: true, signer: true },
        { name: "client" },
        { name: "contractor" },
        { name: "contract", writable: true },
        { name: "config" },
        { name: "mint" },
        { name: "escrowTokenAccount", writable: true },
        { name: "contractorTokenAccount", writable: true },
        { name: "clientTokenAccount", writable: true },
        { name: "tokenProgram" },
      ],
      args: [
        { name: "checkpointIndex", type: "u8" },
        { name: "favorContractor", type: "bool" },
      ],
    },
  ],
  accounts: [
    { name: "ContractAccount", discriminator: [158, 92, 19, 55, 102, 209, 113, 218] },
    { name: "ProgramConfig",   discriminator: [196, 210, 90, 231, 144, 149, 140, 63] },
    { name: "UserMintRecord",  discriminator: [120, 250, 207, 149, 49, 124, 10, 58] },
  ],
  types: [
    {
      name: "CheckpointInput",
      type: {
        kind: "struct",
        fields: [
          { name: "descriptionHash", type: "string" },
          { name: "paymentAmount", type: "u64" },
          { name: "deadline", type: "i64" },
        ],
      },
    },
    {
      name: "CheckpointData",
      type: {
        kind: "struct",
        fields: [
          { name: "checkpointNumber", type: "u8" },
          { name: "descriptionHash", type: "string" },
          { name: "evidenceHash", type: "string" },
          { name: "aiReportHash", type: "string" },
          { name: "paymentAmount", type: "u64" },
          { name: "penaltyAmount", type: "u64" },
          { name: "effectivePayment", type: "u64" },
          { name: "status", type: { defined: { name: "CheckpointStatus" } } },
          { name: "deadline", type: "i64" },
          { name: "newDeadlineRequested", type: "i64" },
          { name: "revisionCount", type: "u8" },
          { name: "submittedAt", type: "i64" },
          { name: "reviewedAt", type: "i64" },
        ],
      },
    },
    {
      name: "ContractStatus",
      type: {
        kind: "enum",
        variants: [
          { name: "Draft" },
          { name: "Active" },
          { name: "Completed" },
          { name: "Cancelled" },
        ],
      },
    },
    {
      name: "CheckpointStatus",
      type: {
        kind: "enum",
        variants: [
          { name: "Pending" },
          { name: "ExtensionPending" },
          { name: "Submitted" },
          { name: "Approved" },
          { name: "NeedsRevision" },
          { name: "Expired" },
          { name: "Disputed" },
          { name: "AwaitingAiReview" },
        ],
      },
    },
    {
      name: "ContractAccount",
      type: {
        kind: "struct",
        fields: [
          { name: "client", type: "pubkey" },
          { name: "contractor", type: "pubkey" },
          { name: "mint", type: "pubkey" },
          { name: "contractHash", type: "string" },
          { name: "aiReviewHash", type: "string" },
          { name: "totalAmount", type: "u64" },
          { name: "totalCheckpoints", type: "u8" },
          { name: "completedCheckpoints", type: "u8" },
          { name: "status", type: { defined: { name: "ContractStatus" } } },
          { name: "createdAt", type: "i64" },
          { name: "bump", type: "u8" },
          { name: "latePenaltyPerDayBps", type: "u16" },
          { name: "maxPenaltyBps", type: "u16" },
          { name: "disputeWindowDays", type: "u8" },
          { name: "gracePeriodDays", type: "u8" },
          { name: "maxRevisionsPerCheckpoint", type: "u8" },
          { name: "checkpoints", type: { vec: { defined: { name: "CheckpointData" } } } },
        ],
      },
    },
    {
      name: "ProgramConfig",
      type: {
        kind: "struct",
        fields: [
          { name: "admin", type: "pubkey" },
          { name: "aiAgent", type: "pubkey" },
          { name: "mint", type: "pubkey" },
          { name: "totalMinted", type: "u64" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "UserMintRecord",
      type: {
        kind: "struct",
        fields: [
          { name: "user", type: "pubkey" },
          { name: "lastMintAt", type: "i64" },
          { name: "bump", type: "u8" },
        ],
      },
    },
  ],
} as const;

export type ContractIDL = typeof IDL;
